server:
  port: 10001
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: sell
  datasource:
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver