server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
spring:
  application:
    name: sell
  datasource:
    url: jdbc:mysql://localhost:3306/sell?characterEncoding&serverTimezone=UTC&useSSL=true
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver